sudo: required
services:
  - docker

before_install:
  - docker  build -t hijazi313/docker-react-production -f Dockerfile.dev .

script:
  - docker run hijazi313/docker-react-production npm run test -- --coverage
